# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a16dec73e28dfa496c53ef4fa740987d63449d9ed0ad4b5b92fd7d71f775265658b7b89789056284e848168c87480fb251978d9f2e30e4695f33347a2e823176

test:
  secret_key_base: daf613578efda348c855ea4bce89340496a33ac1e59333b6ed8699e89cafe34ad81278f3481eb138043c426bd37de77a0a46510e95facff052e8828f7b2900fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
